on: 
    push:
        branches: 
        - develop
    workflow_dispatch:
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: setup dotnet
       uses: actions/setup-dotnet@v4
       with: 
        dotnet-version: 9.0.x
     - name: restore the dependencies
       run: dotnet restore src/Presentation/Nop.Web/Nop.Web.csproj
     - name: compile the application
       run: dotnet build --configuration=Release src/Presentation/Nop.Web/Nop.Web.csproj --no-restore
     - name: test the application
       run: dotnet test src/Tests/Nop.Tests/Nop.Tests.csproj
     - name: publish the project
       run: dotnet publish --configuration Release src/Presentation/Nop.Web/Nop.Web.csproj --output published

        