on: 
    push:
        branches: 
        - develop
    workflow_dispatch:
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: setup dotnet
       uses: actions/setup-dotnet@v4
       with: 
        dotnet-version: 9.0.x
     - name: restore the dependencies
       run: dotnet restore .src/Presentation/Nop.Web/Nop.Web.csproj
        